Config:
  rollback:
    # Sets the time (in miliseconds) at which the plugin stops doing whatever it's doing
    # and continues next tick. Each tick is 50 miliseconds, so it should be below that.
    # The default time is 25ms since that is half of a tick. If your server lags,
    # try lowering this value.
    # If the server's TPS are fine, raise this number if you want it to work quicker.
    targettime: 25
    # Compression. Compression can slow it down, but it also lowers the amount of
    # storage that is required.
    # "LZ4" offers about a 40% reduction with minimal overhead.
    # GZip is currently unavailable (and is slower)
    # "none" is default because it lowers the chance of data corruption
    compression: "none"
    # Whether or not the plugin should manually unload chunks.
    # This may lower ram usage, expecially when the rollback paste is large.
    unload_chunks: false
  arenas:
    examplearena:
      x: 1
      y: 1
      z: 1
      world: "world"
custom-mappings: []
# Don't change configversion. It may cause issues in the future if the config changes!
configversion: 1.0
