name: RollbackCore
main: net.shadowxcraft.rollbackcore.Main
version: 3.3.0-BETA
api-version: 1.13
softdepend: [WorldEdit]
commands:
  rollback:
    usage: /rollback <paste/copy/reload>
    description: Copies/Saves a region.
    permission: rollback.admin
    aliases: [rb, /rollback]
permissions:
    rollback.admin:
        description: Used to save and load arenas.
        default: op